#! /bin/sh

# ibus
ibus-daemon -drxR

# shortcuts
pgrep -x sxhkd >/dev/null || sxhkd &

# top bar
$HOME/.config/polybar/launch.sh

# restore screen brightness
brightnessctl --restore

# wallpaper
nitrogen --set-zoom /media/pomp/data/Pictures/Wallpapers/cozy_blur.png

# system monitor
$HOME/.local/bin/pomky

# monitor
bspc monitor -d 1 2 3 4 5

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false
