MCU = atmega32u4             #
BOOTLOADER = atmel-dfu       #
BOOTMAGIC_ENABLE = no        # Virtual DIP switch configuration
MOUSEKEY_ENABLE = yes        #
EXTRAKEY_ENABLE = no         # Audio control and System control
CONSOLE_ENABLE = no          # Console for debug
COMMAND_ENABLE = no          # Commands for debug and configuration
SLEEP_LED_ENABLE = no        # Breathing sleep LED during USB suspend (DO NOT ENABLE. it uses the same timer as BACKLIGHT_ENABLE)
NKRO_ENABLE = yes            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no        # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no         # Enable keyboard RGB underglow
AUDIO_ENABLE = no            # Audio output on port C6
FAUXCLICKY_ENABLE = no       # Use buzzer to emulate clicky switches
MIDI_ENABLE = no             #
UNICODE_ENABLE = no          # 
BLUETOOTH_ENABLE = no        # Enable Bluetooth with the Adafruit EZ-Key HID
DEBOUNCE_TYPE = sym_eager_pk # https://github.com/qmk/qmk_firmware/blob/master/docs/feature_debounce_type.md
DEBOUNCE = 5                 #
